pipeline {
  agent any
  environment {
    IMAGE_NAME = "dprashanthkumar/devops-python-app"
  }
  stages {
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t $IMAGE_NAME:latest -f Terraform/docker/Dockerfile .'
      }
    }
    stage('Push Image') {
      steps {
        withCredentials([usernamePassword(credentialsId:'dockerhub-credentials',usernameVariable:'DOCKER_USER' ,passwordVariable:'DOCKER_PASS')]) {
          sh ''' echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin docker push $IMAGE_NAME:latest'''
        }
      }
    }
  }
}
